config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :suppliers, only: [] do
    collection do
      get :search
      post :search
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController

  def search
    if request.post?
      @result = nil
      search = SearchSupplier.new
      if params["postcode"].present?
        @result = search.fetch_supplier(params["postcode"])
      else
        @result = 'Please insert valid postcode'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/home/index.html.erb
<%= render :partial => "suppliers/form" %>

app/views/home/search_supplier.html.erb
<%= render :partial => "suppliers/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WaterSupplier" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">WaterSupplier</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3"></div>
      </div>
    </div>
  </body>
</html>

app/views/suppliers/_form.html.erb
<%= form_tag(search_suppliers_path) do %>
  <div class="form-group">
    <div class="input-group input-group-lg">
      <span class="input-group-addon">Postcode</span>
      <%= text_field_tag :postcode, params["postcode"] , :class => "form-control", :placeholder => "Enter your postcode..." %>
    </div>
  </div>

  <div class="form-group">
    <%= submit_tag "Search Supplier" , class: "btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

<div class="row" align="center">
  <h3><%= @result %></h3>
</div>

app/views/suppliers/search.html.erb
<%= render partial: 'form'%>